### ISSUE TITLE
No such file or directory: 'randooped1\\classes-to-analyze'

### ISSUE THREAD

**Issue by MarwenSami** [psycopaths/jdoop#1]
Hello,
I installed JDart and JDoop successully but when I try to run JDoop I get this error:

Erreur : impossible de trouver ou charger la classe principale $JVM_FLAGS
Traceback (most recent call last):
  File "jdoop.py", line 625, in <module>
    jdoop.generate_jpf_conf(unit_tests, params.root)
  File "jdoop.py", line 330, in generate_jpf_conf
    jpf_configuration_files.run()
  File "C:\Users\msami\Desktop\JDart\jdoop\generate_jpf_files.py", line 89, in run
    with open(os.path.normpath(os.path.join(self.location, self.classes_to_analyze)), 'r') as f:
IOError: [Errno 2] No such file or directory: 'randooped1\classes-to-analyze'

Any Idea ?

Thanks,
Best regards,

**Comment by MarwenSami** [comment]
Well I figured out how to solve this problem but still I got a lot of others, because I'm trying to run JDoop on a windows, so basically I had to change JVM_FLAGS to windows style and classpath separators from ':' to ';' etc... 

Now I get this error:
policy = sun.security.provider.PolicyFile@7ef20235
WARNING: classForName(features\simple.Input) yielded exception: features/simple/Input
java.lang.ClassNotFoundException: features/simple/Input
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at randoop.util.Reflection.classForName(Reflection.java:198)
    at randoop.util.Reflection.loadClassesFromReader(Reflection.java:423)
    at randoop.util.Reflection.loadClassesFromFile(Reflection.java:445)
    at randoop.main.GenInputsAbstract.findClassesFromArgs(GenInputsAbstract.java:562)
    at randoop.main.GenTests.handle(GenTests.java:187)
    at randoop.main.Main.nonStaticMain(Main.java:80)
    at randoop.main.Main.main(Main.java:42)
PUBLIC MEMBERS=1
Explorer = randoop.ForwardGenerator@21b8d17c

**Comment by mdimjasevic** [comment]
@MarwenSami, the first issue should be fixed now. I never tested JDoop on anything other than GNU/Linux. As a matter of fact, there are a few platform-specific things in the code base so I'm expecting it should not work on Windows.

I'm closing the issue.
